import 'package:powersync/powersync.dart';
import 'package:powersync/attachments/attachments.dart';

Schema schema = Schema([
  Table('items', [
    Column.text('timestamp'),
    Column.text('name'),
    Column.text('image'),
  ], viewName: 'items'),
  Table('members', [
    Column.text('timestamp'),
    Column.text('name'),
    Column.text('item_id'),
    Column.integer('color'),
    Column.integer('active'),
    Column.integer('deleted'),
    Column.text('email'),
  ], viewName: 'members'),
  Table('transactions', [
    Column.text('timestamp'),
    Column.text('description'),
    Column.text('item_id'),
    Column.text('member_id'),
    Column.text('payoff_id'),
    Column.real('value'),
    Column.text('date'),
    Column.integer('deleted'),
  ], viewName: 'transactions'),
  Table('operations', [
    Column.text('timestamp'),
    Column.text('item_id'),
    Column.text('member_id'),
    Column.text('transaction_id'),
    Column.real('value'),
  ], viewName: 'operations'),
  Table('shared', [
    Column.text('user_email'),
    Column.text('item_id'),
    Column.text('user_id'),
    Column.integer('full_access'),
    Column.text('expiration_date'),
  ]),
  Table.localOnly('local_items', [
    Column.text('timestamp'),
    Column.text('name'),
    Column.text('image'),
  ], viewName: 'inactive_local_items'),
  Table.localOnly('local_members', [
    Column.text('timestamp'),
    Column.text('name'),
    Column.text('item_id'),
    Column.integer('color'),
    Column.integer('active'),
    Column.integer('deleted'),
    Column.text('email'),
  ], viewName: 'inactive_local_members'),
  Table.localOnly('local_transactions', [
    Column.text('timestamp'),
    Column.text('description'),
    Column.text('item_id'),
    Column.text('member_id'),
    Column.text('payoff_id'),
    Column.real('value'),
    Column.text('date'),
    Column.integer('deleted'),
  ], viewName: 'inactive_local_transactions'),
  Table.localOnly('local_operations', [
    Column.text('timestamp'),
    Column.text('item_id'),
    Column.text('member_id'),
    Column.text('transaction_id'),
    Column.real('value'),
  ], viewName: 'inactive_local_operations'),
  AttachmentsQueueTable(),
]);

Schema localSchema = Schema([
  Table('items', [
    Column.text('timestamp'),
    Column.text('name'),
    Column.text('image'),
  ], viewName: 'inactive_synced_items'),
  Table('members', [
    Column.text('timestamp'),
    Column.text('name'),
    Column.text('item_id'),
    Column.integer('color'),
    Column.integer('active'),
    Column.integer('deleted'),
    Column.text('email'),
  ], viewName: 'inactive_synced_members'),
  Table('transactions', [
    Column.text('timestamp'),
    Column.text('description'),
    Column.text('item_id'),
    Column.text('member_id'),
    Column.text('payoff_id'),
    Column.real('value'),
    Column.text('date'),
    Column.integer('deleted'),
  ], viewName: 'inactive_synced_transactions'),
  Table('operations', [
    Column.text('timestamp'),
    Column.text('item_id'),
    Column.text('member_id'),
    Column.text('transaction_id'),
    Column.real('value'),
  ], viewName: 'inactive_synced_operations'),
  Table.localOnly('local_items', [
    Column.text('timestamp'),
    Column.text('name'),
    Column.text('image'),
  ], viewName: 'items'),
  Table.localOnly('local_members', [
    Column.text('timestamp'),
    Column.text('name'),
    Column.text('item_id'),
    Column.integer('color'),
    Column.integer('active'),
    Column.integer('deleted'),
    Column.text('email'),
  ], viewName: 'members'),
  Table.localOnly('local_transactions', [
    Column.text('timestamp'),
    Column.text('description'),
    Column.text('item_id'),
    Column.text('member_id'),
    Column.text('payoff_id'),
    Column.real('value'),
    Column.text('date'),
    Column.integer('deleted'),
  ], viewName: 'transactions'),
  Table.localOnly('local_operations', [
    Column.text('timestamp'),
    Column.text('item_id'),
    Column.text('member_id'),
    Column.text('transaction_id'),
    Column.real('value'),
  ], viewName: 'operations'),
  AttachmentsQueueTable(),
]);